name: focusd

windows:
  - editor: nvim :SessionLoad focusd

  - test/run:
      layout: main-vertical
      panes:
        -
        - focusd-dev --daemon
        - Build: fd -e rs | entr -r cargo build --no-default-features --features dev-build
  - SQL: sqlite3 ~/.local/share/focusd/db/history-dev.db
  - misc:
