[package]
name = "focusd"
version = "0.2.0"
edition = "2024"
authors= ["bibekbhusal0"]
description = "A beautiful terminal pomodoro timer with daemon, waybar integration and interactive TUI"
documentation = "https://github.com/bibekbhusal0/focusd"
homepage = "https://github.com/bibekbhusal0/focusd"
repository = "https://github.com/bibekbhusal0/focusd"
readme = "README.md"
keywords = ["productivity", "timer", "pomodoro"]
categories = ["command-line-interface"]
license = "MIT"
exclude = [
    "assets/*",
    "scripts/*",
]

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
rusqlite = { version = "0.40.1", default-features = false }
chrono = { version = "0.4.45" }
notify-rust = "4.18.0"
figlet-rs = "1.0.0"
serde_json = "1.0"
tui-piechart = "1.0.0"
clap = {version =  "4.6.4", features = ["derive"] }
tui-widget-list = "0.15.3"
toml_edit = "0.25.13"
tui-input = "0.15.3"
ratatui-themes = "0.3.0"

[features]
default = ["bundled-sqlite"]
bundled-sqlite = ["rusqlite/bundled"]
dev-build = []
